name       : python-qrcode
version    : 7.3.1
release    : 6
source     :
    - https://pypi.io/packages/source/q/qrcode/qrcode-7.3.1.tar.gz : 375a6ff240ca9bd41adc070428b5dfc1dcfbb0f2507f1ac848f6cded38956578
license    : BSD-3-Clause
component  : programming.python
summary    : QR Code image generator
description: |
    QR Code image generator
builddeps  :
    - pkgconfig(python3)
    - python-pillow
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
