name       : python-qrcode
version    : 5.3
release    : 1
source     :
    - https://pypi.python.org/packages/87/16/99038537dc58c87b136779c0e06d46887ff5104eb8c64989aac1ec8cba81/qrcode-5.3.tar.gz : 4115ccee832620df16b659d4653568331015c718a754855caf5930805d76924e
license    : BSD-3-Clause
component  : programming.python
summary    : QR Code image generator
description: |
    QR Code image generator
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
rundeps    :
    - python-pillow
build      : |
    %python_setup
install    : |
    %python_install
