name       : python-qrcode
version    : '6.1'
release    : 5
source     :
    - https://pypi.io/packages/source/q/qrcode/qrcode-6.1.tar.gz : 505253854f607f2abf4d16092c61d4e9d511a3b4392e60bff957a68592b04369
license    : BSD-3-Clause
component  : programming.python
summary    : QR Code image generator
description: |
    QR Code image generator
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-pillow
build      : |
    %python3_setup
install    : |
    %python3_install
